### PR TITLE
HACS folder layout

### PR DESCRIPTION
**Pull request by dfigus**
Switch to HACS folder layout so that the custom component can be managed via [HACS](https://hacs.xyz/).

### CODE REVIEW

**Comment by W00D00** [comment]
Hi @dfigus,

many thanks for your cooperation.
Did you test your change with a real HACS install? 
Please, update the versioning and create a new version based on your commit or if you don't know how to do it I'll do it just inform me about it.

Thanks,
István

**Comment by dfigus** [comment]
@W00D00 I did install it with HACS from my fork, so yes it was a real HACS install 😀. With update the versioning, I guess you mean update the version inside the manifest.json and afterwards create a Github release? Or something else?

**Comment by W00D00** [comment]
Hi @dfigus,

Great, thanks.

Yes, please update the "__version__ = "3.1.0"" to 3.2.0 in the __init__.py and the cover.py and the manifest.json too. thanks

**Comment by dfigus** [comment]
@W00D00: Created #32 for the version bump 😎

**Comment by caco3** [comment]
Thanks for your work!
Will it be visible in HACS or will I need to enter the repo URL manually?
What is the best way to migrate? Is it ok to delete the custom component and add itvia HACS?

**Comment by dfigus** [comment]
@caco3 You need to add it as a custom repository. I updated the README.md with a short section about HACS in the PR #32. Feel free to review it and/or propose improvements in that new PR.

**Comment by caco3** [comment]
@dfigus Thanks for the update.

Please add following line to the README.md changelog:
* 3.2.0 - March 10, 2021 [Added support for HACS](https://github.com/W00D00/home-assistant-elero/issues/23)

I tested it with your repo (https://github.com/dfigus/home-assistant-elero/tree/version_bump), how ever it seems always to grab the files from master (version was still on 3.1.0, so I replaced them manually from your branch.
Then it worked fine.

**Comment by Schnabulation** [comment]
Hey guys
I still have trouble installing this with HACS. I get an error that version 3.1.0 does not have the correct HACS folder layout.
Am I doing something wrong?

**Comment by dfigus** [comment]
@Schnabulation We need PR #32 to be merged and a new version created afterwards by @W00D00 . The problem is that version 3.1.0 is still using the old folder layout. You can use my fork https://github.com/dfigus/home-assistant-elero that does not have any releases and hence installs just the latest commit from the master branch.

**Pull request merged**
